config/routes.rb
Blogger::Application.routes.draw do
	root to: 'hosts#index' 
	resources :articles

	resources :articles do
  		resources :comments
	end

	resources :tags		
	
	resources :hosts 
	match '/listAll',  to: 'hosts#listAllHost',            via: 'get'
end

app/models/article.rb
class Article < ActiveRecord::Base
	attr_accessible :title, :body, :tag_list, :image

	has_many :comments
	has_many :taggings
	has_many :tags, :through => :taggings

	has_attached_file :image

	def tag_list
		return self.tags.join(", ")
	end

	def tag_list=(tags_string)
    		self.taggings.destroy_all

		tag_names = tags_string.split(",").collect{|s| s.strip}.uniq

		tag_names.each do |tag_name|
			tag = Tag.find_or_create_by_name(tag_name)
			tagging = self.taggings.new
			tagging.tag_id = tag.id
		end
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
  		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article.id
	end
	
	def new
		@article = Article.new
		@comment = Comment.new
		@comment.article_id = @article.id
	end

	def create
  		@article = Article.new(article_params)	
		@article.save
		flash.notice = "O artigo [#{@article.title}] foi criado!"
  		redirect_to article_path(@article)
	end

  def destroy
    @article = Article.find(params[:id])

    @article.destroy
    flash.notice = "O artigo [#{@article.title}] foi excluido!"

    redirect_to articles_path
  end


  	def article_params
    		params.require(:article).permit(:title, :body, :tag_list)
  	end

	def edit
  		@article = Article.find(params[:id])
	end

	def update
  		@article = Article.find(params[:id])
  		@article.update(article_params)

		flash.notice = "O artigo [#{@article.title}] foi modificado!"

  		redirect_to article_path(@article)
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comment.html.erb
<div>
  	<h4>Comment by <%= comment.author_name %></h4>
  	<p class="comment"><%= comment.body %></p>
	<p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
  	<%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.label :image, "Attach an Image" %><br />
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1> Todos os artigos</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
	<%= link_to article.title, article_path(article),
    		class: 'article_title', id: "article_#{article.id}" %>
    </li>
  <% end %>
  <%= link_to "Create a New Article", new_article_path, class: "new_article" %>

</ul>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h3>Lista dos artigos disponíveis</h3>
<p><%= @article.title %></p>
<p><%= @article.body %></p>
<%= link_to "<< Back to Articles List", articles_path %>

<h3>Deletando o artigo</h3>
<%= link_to "delete", article_path(@article), method: :delete %>

<h3>Editando o artigo</h3>
<%= link_to "edit", edit_article_path(@article) %>

<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'comments/form' %>
<%= render partial: 'articles/comment', collection: @article.comments %>

<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>