config/routes.rb
Blogger::Application.routes.draw do
	root to: 'hosts#index' 
	resources :articles

	resources :articles do
  		resources :comments
	end

	resources :tags		
	
	resources :hosts 
	match '/listAll',  to: 'hosts#listAllHost',            via: 'get'
end

app/models/host.rb
class Host < ActiveRecord::Base
end

app/controllers/hosts_controller.rb
require 'snmp'

class HostsController < ApplicationController
  def index
  		@hosts = Host.all
  end
  
  def show
  	@host = Host.find(params[:id])
  end
  
  def new
  	@host = Host.new
  end
  
  def create
  	@host = Host.new(host_params)	
  	
  	@host.hostName = "adenir.centralit"
  	@host.save
  	flash.notice = "O Host [#{@host.hostName} #{@host.description} #{@host.snmp_userName}] foi criado!"
  	redirect_to host_path(@host)
  end
  
  def destroy
    @host = Host.find(params[:id])

    @host.destroy
    flash.notice = "O host [#{@host.hostName}] foi excluido!"

    redirect_to hosts_path
  end

  def host_params
  		params.require(:host).permit(:hostName, :description, :snmp_community, :snmp_version, :snmp_userName, :snmp_password)    

  end
    
  def edit
  	@host = Host.find(params[:id])
    SNMP::Manager.open(:host => 'localhost') do |manager|
        response = manager.get(["sysDescr.0", "sysName.0"])
        response.each_varbind do |vb|
            @host.hostName = vb.name.to_s
            @host.description = vb.value.to_s
            @host.snmp_userName = vb.value.asn1_type
        end
    end
  end
  
  def update
  	@host = Host.find(params[:id])
  	@host.update(host_params)
  
    flash.notice = "O Host [#{@host.hostName}] foi modificado!"
  
  	redirect_to host_path(@host)
  end

  def listAllHost
    #arp-scan --interface=eth0 192.168.0.0/24
    #!/bin/bash
    #for ip in 192.168.0.{1..254}; do
      #  ping -c 1 -W 1 $ip | grep "64 bytes" &
    #done
    
    @host = Host.new
    SNMP::Manager.open(:host => 'localhost') do |manager|
        response = manager.get(["sysDescr.0", "sysName.0"])
        response.each_varbind do |vb|
            @host.hostName = vb.name.to_s
            @host.description = vb.value.to_s
            @host.snmp_userName = vb.value.asn1_type
            flash.notice = "O Host [#{@host.hostName} #{@host.description} #{@host.snmp_userName}] foi criado!"
        end
    end
    
    render :action => "new"
   end 
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/hosts/_form.html.erb
<%= form_for(@host, html: {multipart: true}) do |f| %>
  <ul>
  <% @host.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  
  <p>
    <%= f.label 'Host Name' %><br />
    <%= f.text_field :hostName %>
  </p>
  
  <p>
    <%= f.label 'Description' %><br />
    <%= f.text_area :description %>
  </p>
  
  <p>
    <%= f.label 'snmp community' %><br />
    <%= f.text_field :snmp_community %>
  </p>
  
  <p>
    <%= f.label 'snmp version' %><br />
    <%= f.text_field :snmp_version %>
  </p>
  
  <p>
    <%= f.label 'snmp user name' %><br />
    <%= f.text_field :snmp_userName %>
  </p>
  
  <p>
    <%= f.label 'snmp password' %><br />
    <%= f.text_field :snmp_password %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/hosts/edit.html.erb
<h1>Edit an Host</h1>
<%= render partial: 'form' %>

app/views/hosts/index.html.erb
<h1> Todos os hosts</h1>

<ul id="hosts">
  <% @hosts.each do |host| %>
    <li>
	<%= link_to host.hostName, host_path(host),
    		class: 'host_hostName', id: "host_#{host.id}" %>   		
    </li>
  <% end %>
  
  <%= link_to "Create a New host", new_host_path, class: "new_host" %>

</ul>

app/views/hosts/new.html.erb
<h1>Create a New host</h1>
<%= render partial: 'form' %>

app/views/hosts/show.html.erb
<h3>Lista do hosts disponíveis</h3>
<p><%= @host.hostName %></p>
<p><%= @host.description %></p>
<%= link_to "<< Back to hosts List", hosts_path %>

<h3>Deletando o host</h3>
<%= link_to "delete", host_path(@host), method: :delete %>

<h3>Editando o host</h3>
<%= link_to "edit", edit_host_path(@host) %>